[project]
name = "divide-and-conquer-sentiment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.12"
dependencies = [
    "torch",
    "pydantic",
    "spacy",
    "pysbd",
    "claucy @ git+https://github.com/mmxgn/spacy-clausie.git"
]
